title: Bureau for etc.
tagline: "International Bureau for Extra-Terrestrial Communications, we publish books."

# Use this for production
#sass:
#    style: :compressed
#url: http://localhost:4000
url: https://pbouigue.github.io/bureauforetc

exclude: [.scss, node_modules, gruntfile.js, package.json]